spring:
  application:
    name: transferservice

  mongodb:
    uri: ${SPRING_MONGODB_URI}


  kafka:
    #    bootstrap-servers: localhost:9092  #para local
    bootstrap-servers: kafka:29092
    consumer:
      group-id: transferGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: >
          funds-reserved-event:com.microservice.transferservice.kafka.event.FundsReservedEvent,
          funds-reservation-failed-event:com.microservice.transferservice.kafka.event.FundsReservationFailedEvent,
          funds-debited-event:com.microservice.transferservice.kafka.event.FundsDebitedEvent,
          funds-credited-event:com.microservice.transferservice.kafka.event.FundsCreditedEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: >
          transfer-requested-event:com.microservice.transferservice.kafka.event.TransferRequestedEvent,
          transfer-debit-requested-event:com.microservice.transferservice.kafka.event.TransferDebitRequestedEvent,
          transfer-credit-requested-event:com.microservice.transferservice.kafka.event.TransferCreditRequestedEvent

server:
  port: 8080

#Healthcheck actuator
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    mongodb:
      enabled: true

  info:
    env:
      enabled: true


jwt:
  secret: ${SECRET_KEY}

logging:
  pattern: # PARA EL CORRELATIONAL ID - LO MOSTRAMOS EN LOG
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{correlationId}] %-5level %logger - %msg%n"

